language: python
dist: xenial
branches:
  only:
    - master
services:
  - docker
sudo: required
before_install:
  - docker-compose -f .travis/docker-compose-travis.yml up -d
install:
  - pip install -r requirements/travis.txt
script:
  - docker exec -t -e TRAVIS=1 analytics_api_testing bash -c " cd /edx/app/analytics_api/analytics_api/
    && make $TARGETS "
matrix:
  include:
    - python: '3.8'
      env: TESTNAME=quality-python-3.8 TARGETS="PYTHON_ENV=py38 quality"
    - python: '3.8'
      env: TESTNAME=test-python-3.8 TARGETS="PYTHON_ENV=py38 test"
    - python: '3.8'
      env: TESTNAME=test-python-3.8-django-3.0 TARGETS="PYTHON_ENV=py38 DJANGO_VERSION=django30 test"
      after_success:
        - docker exec analytics_api_testing /edx/app/analytics_api/analytics_api/.travis/run_coverage.sh
        - codecov --disable pycov
env:
  global:
    - DOCKER_USERNAME=edxbuilder
    - secure: ax2wADc8m84sUqM8QQ7px7zEGXPQWqAIr53ZIvbN9NP/Mco9oB1TmjRgo7dP4iRKMflB2F51owT3IyS8S7E8jTfemgDwrJaKb+iobulPHk0Gu4f0ywPBYcIAV77uLvSGL3DmkEzq5MFyK9vOldpAry/9n59h8lobkhA12Wup9w4=
deploy:
  provider: script
  script: make travis_docker_push
  on:
    branch: master
