language: python
dist: xenial
branches:
  only:
  - master
services:
- docker
sudo: required
before_install:
- docker-compose -f .travis/docker-compose-travis.yml up -d
install:
- pip install -r requirements/travis.txt
script:
- docker exec -t -e TRAVIS=1 analytics_api_testing bash -c " cd /edx/app/analytics_api/analytics_api/
  && export TOXENV=django32 && make $TARGETS "
matrix:
  include:
  - python: '3.8'
    env: TESTNAME=install-requirements TARGETS="test.requirements"
  - python: '3.8'
    env: TESTNAME=quality-python-3.8 TARGETS="quality"
  - python: '3.8'
    env: TESTNAME=test-python-3.8 TARGETS="main.test"
    after_success:
    - docker exec analytics_api_testing /edx/app/analytics_api/analytics_api/.travis/run_coverage.sh
    - codecov --disable pycov
  - python: '3.8'
    env: TESTNAME=docs TARGETS="docs"
env:
  global:
  - DOCKER_USERNAME=edxbuilder
  - secure: YXlXo4K2VQZXA8divHuXy/g71wGA3rYlyuJgrF7YVkaxUg8mIk0whq1feSQbBbrpvObTJS7yz1wrIVTyfVCxDVecyPPSv1MXvpqzf8RhVxA3o++9iBSnaIdKCnVTsd3H/ENn0EgNFHsOPQRQ14rT205CU3p35s9wSuLVXojV++8=
deploy:
  provider: script
  script: make travis_docker_push
  on:
    branch: master
